bloodbank/bloodbankmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LogoutView,LoginView
from blood import views
urlpatterns = [
    path('admin/', admin.site.urls),

    
    path('donor/',include('donor.urls')),
    path('patient/',include('patient.urls')),

    
    path('',views.home_view,name=''),
    path('logout', LogoutView.as_view(template_name='blood/logout.html'),name='logout'),

    path('afterlogin', views.afterlogin_view,name='afterlogin'),
    path('adminlogin', LoginView.as_view(template_name='blood/adminlogin.html'),name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),
    path('admin-blood', views.admin_blood_view,name='admin-blood'),
    path('blood-cost/', views.cost_of_blood, name='blood-cost'),
    path('admin-donor', views.admin_donor_view,name='admin-donor'),
    path('admin-patient', views.admin_patient_view,name='admin-patient'),
    path('update-donor/<int:pk>', views.update_donor_view,name='update-donor'),
    path('delete-donor/<int:pk>', views.delete_donor_view,name='delete-donor'),
    path('admin-request', views.admin_request_view,name='admin-request'),
    path('update-patient/<int:pk>', views.update_patient_view,name='update-patient'),
    path('delete-patient/<int:pk>', views.delete_patient_view,name='delete-patient'),
    path('admin-donation', views.admin_donation_view,name='admin-donation'),
    path('approve-donation/<int:pk>', views.approve_donation_view,name='approve-donation'),
    path('reject-donation/<int:pk>', views.reject_donation_view,name='reject-donation'),
    path('admin-request-history', views.admin_request_history_view,name='admin-request-history'),
    path('update-approve-status/<int:pk>', views.update_approve_status_view,name='update-approve-status'),
    path('update-reject-status/<int:pk>', views.update_reject_status_view,name='update-reject-status'),
   
]

bloodbank/donor/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView
from . import views
urlpatterns = [
    path('donorlogin', LoginView.as_view(template_name='donor/donorlogin.html'),name='donorlogin'),
    path('donorsignup', views.donor_signup_view,name='donorsignup'),
    path('donor-dashboard', views.donor_dashboard_view,name='donor-dashboard'),
    path('donate-blood', views.donate_blood_view,name='donate-blood'),
    path('donation-history', views.donation_history_view,name='donation-history'),
    path('make-request', views.make_request_view,name='make-request'),
    path('request-history', views.request_history_view,name='request-history'),
]

bloodbank/patient/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView
from . import views
urlpatterns = [
    path('patientlogin', LoginView.as_view(template_name='patient/patientlogin.html'),name='patientlogin'),
    path('patientsignup', views.patient_signup_view,name='patientsignup'),
    path('patient-dashboard', views.patient_dashboard_view,name='patient-dashboard'),
    path('make-request', views.make_request_view,name='make-request'),
    path('my-request', views.my_request_view,name='my-request'),
    path('initiate-pyment/', views.initiate_payment, name='initiate-payment'),
    path('<str:ref>/', views.verify_payment, name='verify-payment'),
]

bloodbank/patient/models.py
import secrets
from urllib import request
from django.db import models
from django.contrib.auth.models import User
from .paystack import PayStack
class Patient(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/Patient/',null=True,blank=True)

    age=models.PositiveIntegerField()
    bloodgroup=models.CharField(max_length=10) 
    disease=models.CharField(max_length=100)
    doctorname=models.CharField(max_length=50)

    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
   
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_instance(self):
        return self
    def __str__(self):
        return self.user.first_name
    


class PaystackPayment(models.Model):
    amount = models.PositiveIntegerField()
    ref = models.CharField(max_length=100)
    email = models.EmailField()
    verified = models.BooleanField(default=False)
    date_paid = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-date_paid', )
        
    def __str__(self):
        return f"An amount of {self.amount} has being paid for blood"
    
    def save(self, *args, **kwargs):
        while not self.ref:
            ref = secrets.token_urlsafe(50)
            object_with_similar_ref = PaystackPayment.objects.filter(ref = ref)
            if not object_with_similar_ref:
                self.ref = ref
            super().save()
        
    def amount_value(self):
        return self.amount * 100
    
    def verify_payment(self):
        paystack = PayStack()
        result = paystack.verify_payment(self.ref, self.amount)
        if result:
            self.verified = True
            self.save()
            if not self.verified:
                return True
            return False

bloodbank/patient/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.models import User
from . import models


class PatientUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password']
        widgets = {
        'password': forms.PasswordInput()
        }

class PatientForm(forms.ModelForm):
    
    class Meta:
        model=models.Patient
        fields=['age','bloodgroup','disease','address','doctorname','mobile','profile_pic']


class PaystackPaymentForm(forms.ModelForm):
    class Meta:
        model = models.PaystackPayment
        fields = ['amount', 'email']

bloodbank/patient/views.py
from email import message
from django.contrib import messages
from django.shortcuts import get_object_or_404, render,redirect,reverse
from django.urls import is_valid_path
from . import forms,models
from django.db.models import Sum,Q
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required,user_passes_test
from django.conf import settings
from datetime import date, timedelta
from django.core.mail import send_mail
from django.contrib.auth.models import User
from blood import forms as bforms
from blood import models as bmodels
from .models import PaystackPayment


def patient_signup_view(request):
    userForm=forms.PatientUserForm()
    patientForm=forms.PatientForm()
    mydict={'userForm':userForm,'patientForm':patientForm}
    if request.method=='POST':
        userForm=forms.PatientUserForm(request.POST)
        patientForm=forms.PatientForm(request.POST,request.FILES)
        if userForm.is_valid() and patientForm.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            patient=patientForm.save(commit=False)
            patient.user=user
            patient.bloodgroup=patientForm.cleaned_data['bloodgroup']
            patient.save()
            my_patient_group = Group.objects.get_or_create(name='PATIENT')
            my_patient_group[0].user_set.add(user)
        return HttpResponseRedirect('patientlogin')
    return render(request,'patient/patientsignup.html',context=mydict)

def patient_dashboard_view(request):
    patient= models.Patient.objects.get(user_id=request.user.id)
    dict={
        'requestpending': bmodels.BloodRequest.objects.all().filter(request_by_patient=patient).filter(status='Pending').count(),
        'requestapproved': bmodels.BloodRequest.objects.all().filter(request_by_patient=patient).filter(status='Approved').count(),
        'requestmade': bmodels.BloodRequest.objects.all().filter(request_by_patient=patient).count(),
        'requestrejected': bmodels.BloodRequest.objects.all().filter(request_by_patient=patient).filter(status='Rejected').count(),

    }
   
    return render(request,'patient/patient_dashboard.html',context=dict)

def make_request_view(request):
    request_form=bforms.RequestForm()
    if request.method=='POST':
        request_form=bforms.RequestForm(request.POST)
        if request_form.is_valid():
            blood_request=request_form.save(commit=False)
            blood_request.bloodgroup=request_form.cleaned_data['bloodgroup']
            patient= models.Patient.objects.get(user_id=request.user.id)
            blood_request.request_by_patient=patient
            blood_request.save()
            return redirect('initiate-payment')  
    return render(request,'patient/makerequest.html',{'request_form':request_form})

def my_request_view(request):
    patient= models.Patient.objects.get(user_id=request.user.id)
    blood_request=bmodels.BloodRequest.objects.all().filter(request_by_patient=patient)
    return render(request,'patient/my_request.html',{'blood_request':blood_request})



def initiate_payment(request):
    payment_form = forms.PaystackPaymentForm(request.POST)
    bloodQuantity = bmodels.BloodRequest.objects.last()
    blood_cost = bmodels.CostOfBloodStock.objects.last()
    
    total_price = bloodQuantity.unit * blood_cost.blood_stock_price
    user = request.user
    if request.method == "POST":
        if payment_form.is_valid():
            payment = payment_form.save()
            return render(request, 'patient/makepayment.html', {'payment':payment, 
                                                                'PAYSTACK_TEST_PUBLIC_KEYS':settings.PAYSTACK_TEST_PUBLIC_KEYS})
        else:
            payment_form = forms.PaystackPaymentForm()
    return render(request,'patient/initiatePayment.html',{'payment_form':payment_form, 
                                                          'total_price':total_price, 
                                                          'bloodQuantity':bloodQuantity,
                                                          'user':user})


def verify_payment(request, ref):
    payment = get_object_or_404(PaystackPayment, ref=ref)
    verified = payment.verify_payment()
    if verified:
        messages.success(request, 'Payment verification was successful')
    else:
        payment.verified = True
        messages.error(request, 'Payment varification failed')
    return redirect('make-request')

bloodbank/templates/patient/initiatePayment.html
{%load static%}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css">

    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i"
        rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static " css/main.css" %}"rel="stylesheet" media="all">
    <style>

    </style>
</head>
<style>
    body {
        background: rgb(43, 98, 124);
    }

    .form-card {
        width: 30rem;
        background-color: black;
        padding: 1rem;
    }

    .form-card h3 {
        text-align: center;
        color: #fff;
        text-transform: uppercase;
        padding: 1rem;
    }

    .card-heading {
        width: 100%;
    }

    .card-body {
        width: 100%;
        border-radius: 1rem;
    }

    .page-wrapper {
        display: flex;
        align-items: center;
        justify-content: center
    }
</style>

<body>




    <div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
        <div class="wrapper wrapper--w790">
            <br><br><br>
            <div class="card card-5 form-card">
                <div class="card-heading">
                    <h3 class="title">Make Blood Payment</h3>
                </div>
                <div class="card-body" style="background-color: rgba(10, 250, 250, 0.7);">


                    <!-- <form method="POST">
        {% csrf_token %}

        {{payment_form|crispy}}


        <div>
            <button class="btn btn--radius-2 btn-danger" type="submit">Continue With Payment</button>
        </div>
    </form> -->

                  <form method="POST">
                        {% csrf_token %}


                        <div id="div_id_amount" class="form-group"> <label for="id_amount" class=" requiredField">
                                Amount<span class="asteriskField">*</span> </label>
                            <div> <input type="number" name="amount" min="0" value="{{total_price}}"
                                    class="numberinput form-control is-invalid" required id="id_amount">
                                <hr>
                                <p id="error_1_id_amount" class="invalid-feedback">
                                    <strong> {{user}}, you are required to pay GHS {{total_price}} for
                                        {{bloodQuantity.unit}} unit
                                        of blood</strong>
                                </p>
                                <hr>
                            </div>
                        </div>
                        <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField">
                                Email<span class="asteriskField">*</span> </label>
                            <div> <input type="email" name="email" maxlength="254"
                                    placeholder="Enter your email address to continue"
                                    class="emailinput form-control is-invalid" required id="id_email">
                                <p id="error_1_id_email" class="invalid-feedback"><strong>This field is
                                        required.</strong></p>
                            </div>
                        </div>



                        <div>
                            <button class="btn btn--radius-2 btn-danger" type="submit">Continue With Payment</button>
                        </div>

                        <hr>
                    </form>




                </div>
            </div>
        </div>
    </div>


    <script>
        let id_amount = document.getElementById('id_amount');
        let id_user = document.getElementById('id_user');
        id_amount.style.display = 'none';
        id_user.style.display = 'none';
    </script>



    <!-- {% include "blood/footer.html" %} -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>



</html>

bloodbank/templates/patient/makepayment.html
{%load static%}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css">
 
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static "css/main.css" %}"rel="stylesheet" media="all">
    <style>

    </style>
    
  </head>
  <body>



    <div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
        <div class="wrapper wrapper--w790">
            <br><br><br>
            <div class="card card-5">
                <div class="card-heading">
                    <h2 class="title">Confirm Payment</h2>
                </div>
                <div class="card-body" style="background-color: rgba(10, 250, 250, 0.7);">

                        <div>
                            <h3>Confirm payment of: GHS {{payment.amount}} </h3>
                            <br><br>
                            <script src="https://js.paystack.co/v1/inline.js"></script>
                            <button class="btn btn--radius-2 btn-danger" onclick="payWithPayStack()" type="submit" id="djanggo-payWithPayStack-Btn">Confirm Payment</button>
                        </div>
        
                    <br>
                </div>
                <script>
                    function payWithPayStack(){
                        let currency = "GHS";
                        let plan = "";
                        let reference = "{{payment.ref}}";
                        let obj = {
                            key : "{{PAYSTACK_TEST_PUBLIC_KEYS}}",
                            email : "{{payment.email}}",
                            amount : "{{payment.amount_value}}",
                            ref : reference,
                            callback : function(response){
                                window.location.href = "{% url 'verify-payment' payment.ref%}"
                            }
                        }
                        if(Boolean(currency)){
                            obj.currency = currency.toUpperCase()
                        }
                        if(Boolean(plan)){
                            obj.plan = plan
                        }
                        var handler = PaystackPop.setup(obj);
                        handler.openIframe();
                    }
                </script>
            </div>
        </div>
    </div>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

bloodbank/templates/patient/makerequest.html
{% extends 'patient/patientbase.html' %}
{% block content %}
{% load widget_tweaks %}
{%load static%}
<head>
        <!-- Font special for pages-->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

        <!-- Main CSS-->
    
        <link href="{% static "css/main.css" %}"rel="stylesheet" media="all">
</head>
<div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
    <div class="wrapper wrapper--w790">
      
        <div style="margin-left: 70px;" class="card card-5">
            <div class="card-heading">
                <h2 class="title">MAKE BLOOD REQUEST</h2>
            </div>
            <div class="card-body">
                
                <form method="POST" autocomplete="off" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-row">
                        <div class="name">Patient Name</div>
                        <div class="value">
                            <div class="input-group">
                                {% render_field request_form.patient_name|attr:'required:true'  class="input--style-5"  %}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Patient Age</div>
                        <div class="value">
                            <div class="input-group">
                                {% render_field request_form.patient_age|attr:'required:true'  class="input--style-5"  %}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Reason</div>
                        <div class="value">
                            <div class="input-group">
                                {% render_field request_form.reason|attr:'required:true'  class="input--style-5"  %}
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Blood Group</div>
                        <div class="value">
                            <div class="input-group">
                                <div class="rs-select2 js-select-simple select--no-search">
                                    <select name="bloodgroup">
                                        <option disabled="disabled" selected="selected">Choose option</option>
                                        <option>O+</option>
                                        <option>O-</option>
                                        <option>A+</option>
                                        <option>A-</option>
                                        <option>B+</option>
                                        <option>B-</option>
                                        <option>AB+</option>
                                        <option>AB-</option>
                                    </select>
                                    <div class="select-dropdown"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Unit (in ml)</div>
                        <div class="value">
                            <div class="input-group">
                                {% render_field request_form.unit|attr:'required:true'  class="input--style-5"  %}
                            </div>
                        </div>
                    </div>

                    <div>
                        <button class="btn btn--radius-2 btn-danger" type="submit">REQUEST</button>
                    </div>
                </form>
                <br>
                

            </div>
        </div>
    </div>
</div>

{% endblock content %}

bloodbank/templates/patient/my_request.html
{% extends 'patient/patientbase.html' %}
{% block content %}
{% load widget_tweaks %}
{%load static%}

<head>
    <style>
        .label {
     color: white;
     padding: 8px;
   }
   
   .success {background-color: #4CAF50;} /* Green */
   .info {background-color: #2196F3;} /* Blue */
   .warning {background-color: #ff9800;} /* Orange */
   .danger {background-color: #f44336;} /* Red */
   .other {background-color: #e7e7e7; color: black;} /* Gray */
    </style>
   </head>
<br><br>
<div class="container">
    <H4 class="text-center">My Blood Request</H4><br>
    <table class="table table-light table-hover table-bordered table-striped">
        <thead class="bg-info">
            <tr>
                <th scope="col">Patient Name</th>
                <th scope="col">Patient Age</th>
                <th scope="col">Reason</th>
                <th scope="col">Blood Group</th>
                <th scope="col">Unit</th>
                <th scope="col">Date</th>
                <th scope="col">Status</th>
                
            </tr>
        </thead>
        <tbody>
            {% for t in blood_request %}
            <tr>
                <td> {{t.patient_name}}</td>
                
                <td>{{t.patient_age}}</td>
                <td>{{t.reason}}</td>
                <td>{{t.bloodgroup}}</td>
                <td>{{t.unit}}</td>
                <td>{{t.date}}</td>
                {% if t.status == 'Approved' %}
                <td><span class="label success"> Approved</span></td>
                
                {% elif t.status == 'Rejected' %}
                <td><span class="label danger">Rejected</span></td>
                {% else %}
                <td><span style="color: white;margin-left: 0px;" class="label info">Pending</span></td>
                {% endif %}
                

            </tr>
            {% endfor %}

        </tbody>
    
    </table>
</div>


{% endblock content %}

bloodbank/templates/patient/patient_dashboard.html
{% extends 'patient/patientbase.html' %}
{% block content %}
<head>
    <style>
            .xyz{     
        color: blue; 
        font-size: 3ex;   
    }
    </style>
</head>
<br><br>
<div class="container">

 
    <div class="row">
      <div class="col-sm-3">
        <div class="card bg-light">
          <div class="card-body">
              <div class="blood">
                <i class="fas fa-sync-alt xyz"></i>
              </div><br>
              <div>
                Request Made <br>
                  {{requestmade}}
              </div>                            
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card bg-light">
            <div class="card-body">
                <div class="blood">
                  <i class="fas fa-sync xyz"></i>
                </div><br>
                <div>
                    Pending Request <br>
                    {{requestpending}}
                </div>                            
            </div>
          </div>
      </div>

      <div class="col-sm-3">
          <div class="card bg-light">
              <div class="card-body">
                  <div class="blood">
                    <i class="fas fa-check-circle xyz"></i>
                  </div><br>
                  <div>
                       Approved Request<br>
                      {{requestapproved}}
                  </div>                            
              </div>
            </div>
      </div>
      <div class="col-sm-3">
          <div class="card bg-light">
              <div class="card-body">
                  <div class="blood">
                    <i class="fas fa-times-circle xyz"></i>
                  </div><br>
                  <div>
                       Rejected Request <br>
                      {{requestrejected}}
                  </div>                            
              </div>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

bloodbank/templates/patient/patientlogin.html
{%load static%}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css">
 
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static "css/main.css" %}"rel="stylesheet" media="all">
    <style>

    </style>
  </head>
  <body>
    {% include "blood/navbar.html" %}




    <div class="page-wrapper bg-gra-03 p-t-45 p-b-50">
        <div class="wrapper wrapper--w790">
            <br><br><br>
            <div class="card card-5">
                <div class="card-heading">
                    <h2 class="title">Patient Login</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="name">Username</div>
                            <div class="value">
                                <div class="input-group">
                                    {% render_field form.username class="input--style-5"%}

                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Password</div>
                            <div class="value">
                                <div class="input-group">
                                    {% render_field form.password class="input--style-5" %}
                                </div>
                            </div>
                        </div>


                        

                        <div>
                            <button class="btn btn--radius-2 btn-danger" type="submit">Login</button>
                        </div>
                    </form>
                    <br>
                    <p style="text-align: center;">Does not have an account ? <a style="text-decoration: none;" href="/patient/patientsignup">Click here to register</a></p>

                </div>
            </div>
        </div>
    </div>

{% include "blood/footer.html" %}
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>
<!--
developed By : sumit kumar
facebook : fb.com/sumit.luv
youtube : youtube.com/lazycoders
-->